{% set version = "0.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-palmerpenguins
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/palmerpenguins_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/palmerpenguins/palmerpenguins_{{ version }}.tar.gz
  sha256: 2a40d48ba6c7978fdf2a6daf647ccb39cd17590680138931d11194d3dd1a30b4

build:
  merge_build_host: true  # [win]
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('palmerpenguins')"           # [not win]
    - "\"%R%\" -e \"library('palmerpenguins')\""  # [win]

about:
  home: https://allisonhorst.github.io/palmerpenguins/
  dev_url: https://github.com/allisonhorst/palmerpenguins
  license: CC0-1.0
  summary: Size measurements, clutch observations, and blood isotope ratios for adult foraging Adélie, Chinstrap, and Gentoo penguins observed on islands in the Palmer Archipelago near Palmer Station, Antarctica. Data were collected and made available by Dr. Kristen Gorman and the Palmer Station Long Term Ecological Research
    (LTER) Program.
  license_family: CC
  license_file:
    - LICENSE-CC0

extra:
  recipe-maintainers:
    - conda-forge/r
